### PR TITLE
Reduce buffer size and cut tox_iterate by 1/20

### PR DESCRIPTION
**Pull request by Chuongv**
This makes the sound crystal clear. Hopefully won't be here long term.

### CODE REVIEW

**Comment by dvor** [comment]
Sound from Antidote to Antidote? What about other clients?

**Comment by Chuongv** [comment]
Sounds great on old Antidote (1/4) to objcToxDemo (1/20). Going to test it with other clients soon hopefully

**Comment by dvor** [comment]
If you like I can create wiki page with information about sound (and video in the future) quality with other clients (like the gist you've given me before). You will be able to update it with most recent information.

**Comment by Chuongv** [comment]
Oh good idea!

**Comment by dvor** [comment]
[Here it is](https://github.com/Antidote-for-Tox/objcTox/wiki/Audio-status). I've copied old status from your gist, you can update it with `crystal clear` sound :-)

**Pull request merged**
